### PR TITLE
use different BND instructions for openHAB Distribution build

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Good idea to make this configurable. I'd prefer though to have this profile active by default for now as many people will build it (and won't know or forget to activate this profile) locally and would have issues building their addons afterwards. Would that be ok (again, only temporarily until addon builds have been migrated as well)?

**Comment by maggu2810** [comment]
To understand it more detailed: Which people will build it and run into trouble?
People using PDE will rely on p2 repositories used by their target platform.
The official addons target platform will use the p2 repository provided by the openHAB infrastructure.
Does the people you refer to use their own PDE target platform, p2 repository etc.?

The local artifacts created by a openHAB Core build should not matter.

Or don't you care about PDE and IDE but about the consumed bundles by the distro Karaf build?
People that working on a non IDE based approach should be able to set the property -- or not?

If it is activated default, I don't know how to unset it for the Eclipse IDE (openHAB Core) again.



So, dependent of your answer to this comment (the stuff above that line), we could also enable it per default but then we don't need to use profiles / make it configurable at all -- it is only a temporary change.

What do you mean with soon in your comment "the addons change to bnd build system soon", what means "temporarily"?

**Comment by kaikreuzer** [comment]
> People using PDE will rely on p2 repositories used by their target platform.

No, this is not correct, only the IDE uses the target platform, but the Maven build of openhab2-addons uses the local Maven repo artifacts. And everyone working on a binding executes the Maven build as well, at least for the SAT results. And if those people happen to work on openhab-core as well and did a Maven build that left artifacts with requirements in the local repo, they will be in trouble.

> If it is activated default, I don't know how to unset it for the Eclipse IDE (openHAB Core) again.

Are you sure you need it activated in the IDE? Does the bndrun fail without the requirements?

> What do you mean with soon in your comment "the addons change to bnd build system soon", what means "temporarily"?

I mean what we had discussed: That the plan is to get back to a single IDE setup and have all addon projects use bnd as well. I won't commit any date as I very much hope that the community (especially @openhab/2-x-add-ons-maintainers) will help on this task.

**Comment by maggu2810** [comment]
> I mean what we had discussed: That the plan is to get back to a single IDE setup and have all addon projects use bnd as well. I won't commit any date as I very much hope that the community (especially @openhab/2-x-add-ons-maintainers) will help on this task.

IIRC that time you stated that it will take its time and there is no hurry. So "soon" sounds different for me.

**Pull request closed without merging**
